#!/bin/bash

set -eu

# 標準入力解析
if [ -p /dev/stdin ]; then
    TXT=$(cat -)
else
    TXT=$*
fi

function usage_exit()
{
    echo 1>&2 "
Usage:  echo 'hoge strings' [-d ,] [-c 1]
        cat piyo.txt | intxt [-d ,] [-c 1]

    General options
        -i
            INSERT MODE enable
        -d
            select delimiter (',' ':', '\\t', ...)
        -c
            select columns number [0-9]+
        -h
            help (this usage)
"
    exit 1
}

# インサートモード{0:'無効', 1:'有効'}
INSERT=0

# オプション解析
while getopts c:d:ih OPT
do
    case "$OPT" in
        d)  DELIMITER=$OPTARG ;;
        c)  COLUMNS=$OPTARG ;;
        i)  INSERT=1 ;; # INSERT MODE
        h)  usage_exit ;;
        \?) usage_exit ;;
    esac
done
shift $((OPTIND - 1))

# オプション無指定の場合、
# スペース区切りで最後の要素をデフォルトに指定
set +u
if [ -z "${DELIMITER}" ]; then
    DELIMITER=' '
fi
if [ -z "${COLUMNS}" ]; then
    COLUMNS='NF'
fi
set -u

# 空白文字及び改行文字のみ
if [ -z "$TXT" ] ; then
    echo '正しい文字列を入力してください。'
    usage_exit
fi

# インサートモード
if [ $INSERT -eq 1 ]; then
    echo "$TXT" | awk NF \
                | awk -F "${DELIMITER}" "{print \$${COLUMNS}}" \
                | sed -E -e "s/^/('/g" -e "s/$/'), /g" | sed -E '$ s/,//g'
    exit 0
fi

# 1行のスペース区切り
#if [ $(echo -e "$TXT" | wc -l) -eq 1 ];  then
#    # TODO ループせずに正規表現等を使い、スペースごとの文字列を抽出し、整形させる
#    for line in $(echo -e "$TXT"); do
#        echo $line
#    done | awk NF | sed -E -e "s/^/'/g" -e "s/$/', /g" | tr -d '\n' | sed -E -e 's/^/(/g' -e 's/, $/)\n/g'
#    exit 0
#fi

# 複数行の${DELIMITER}区切りの${COLUMNS}カラム目
echo "$TXT" | awk NF \
            | awk -F "${DELIMITER}" "{print \$${COLUMNS}}" \
            | sed -E -e "s/^/'/g" -e "s/$/', /g" | tr -d '\n' | sed -E -e 's/^/(/g' -e 's/, $/)\n/g'
exit 0
