#!/bin/bash

set -eu

# 接続先
HOST_ARRAY=(
inet-ip.info
ifconfig.me
)
regex='^(([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
for host in "${HOST_ARRAY[@]}" ; do
    ip="$(curl -s $host)"
    if [[ $ip =~ $regex ]] ; then
        break
    fi
done

# リザルトを表示
if [[ ! $ip =~ $regex ]] ; then
    'グローバルIPが取得できませんでした。'
    exit 1
else
    echo "$ip"
fi

exit 0
